---
- name: Deploy {{ cookiecutter.role_name }}
  hosts: all
  become: true

  pre_tasks:
    - name: Check if requirements.yml files exists
      stat:
        path: "requirements.yml"
      register: file_data

    - name: install galaxy requirements
      command: ansible-galaxy install -r requirements.yml
      changed_when: false
      delegate_to: localhost
      run_once: true
      check_mode: false
      become: true
      when:
        - file_data.stat.exists


  roles:
    - {role: '{{cookiecutter.role_name}}'}

  post_tasks:
    - name: Get list of Galaxy requirement roles
      shell: ansible-galaxy role list | grep -i '-' | grep -iv '{{cookiecutter.role_name}}' | cut -d ',' -f1 | sed 's/- //g'
      delegate_to: localhost
      check_mode: false
      run_once: true
      changed_when: false
      become: false
      register: galaxy_role_list

    - name: remove galaxy requirements
      #{% raw %}
      command: ansible-galaxy remove {{ item }}
      #{% endraw %}
      changed_when: false
      delegate_to: localhost
      run_once: true
      check_mode: false
      become: false
      with_items:
        #{% raw %}
        - "{{ galaxy_role_list.stdout }}"
        #{% endraw %}
      when:
        - file_data.stat.exists
